version: '3.7'

services:

  server:
    image: "node:15"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DB_SCHEMA=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
      - DB_PORT=${POSTGRES_PORT}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./server:/home/node/app
    ports:
      - "${SERVER_PORT}:3000"
    command: "npm run dev"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"